CREATE TABLE "role_user" (
  "id" int UNIQUE PRIMARY KEY,
  "name_role" varchar(40)
);

CREATE TABLE "categories" (
  "id" int UNIQUE PRIMARY KEY,
  "name" varchar(40) NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "title" varchar(30) UNIQUE NOT NULL,
  "description" varchar(250) NOT NULL,
  "level" varchar(30) NOT NULL,
  "category_id" int UNIQUE NOT NULL,
  "teacher" int NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar(30) NOT NULL,
  "email" varchar(40) NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL,
  "role_id" int NOT NULL
);

CREATE TABLE "videos" (
  "id" int PRIMARY KEY NOT NULL,
  "title" varchar(50) NOT NULL,
  "url" varchar(250)
);

CREATE TABLE "user_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" int,
  "course_id" int
);

CREATE TABLE "courses_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "course_id" int,
  "video_id" int
);

ALTER TABLE "user_courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "role_user" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("id") REFERENCES "courses" ("category_id");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("video_id") REFERENCES "videos" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

-------------------inserts-----------------------
INSERT INTO role_user (id, name_role)
VALUES
(1, 'Student'),
(2, 'Teacher'),
(3, 'Admin');


INSERT INTO users (name,email, password, age, role_id )
VALUES
('Gerardo', 'gerardo@gmail.com', '1234', 35, 1);

INSERT INTO users (name,email, password, age, role_id )
VALUES
('Joel', 'Joel@gmail.com', '123', 29, 1);

INSERT INTO users (name,email, password, age, role_id )
VALUES
('Ian Rosas', 'Ian@gmail.com', '12345', 33, 2);



INSERT INTO courses (title, description, level, category_id, teacher) 
VALUES
('JavaScript', 'Fundaments of JavaScript', 'Basic', 1, 3);

INSERT INTO courses (title, description, level, category_id, teacher) 
VALUES
('Node', 'servers with node', 'intermediate', 2, 3);



INSERT INTO categories (id, name)
VALUES 
(1, 'Programacion'), (2,'Server');



INSERT INTO videos (id, title, url)
VALUES
(1, 'JavaScript Fundaments', 'https://www.youtube.com/watch?v=Z4TuS0HEJP8');

INSERT INTO videos (id, title, url)
VALUES
(2, 'Server with node', 'https://www.youtube.com/watch?v=VShtPwEkDD0');



INSERT INTO courses_videos (course_id, video_id)
VALUES
(1,1),
(2,2);



INSERT INTO user_courses (user_id, course_id)
VALUES
(1, 1),(2,2);

SELECT 
    u.name AS user_name,
    us.name AS teacher_name, 
    v.title AS video_title
FROM 
    users u
JOIN 
    user_courses uc ON u.id = uc.user_id
JOIN 
    courses c ON uc.course_id = 1
JOIN 
    users us ON us.id = c.teacher
JOIN 
    courses_videos cv ON c.id = cv.course_id
JOIN 
    videos v ON cv.video_id = v.id
WHERE 
    c.id = 1;
---consulta alumnos, maestros, categoria y videos del curso 1

SELECT
    u.name AS user_name,
    v.title AS video_title,
    c.title AS course_title,
    us.name AS teacher_name, 
    c.level AS course_level,
    c.description AS course_description,
    cat.name AS category_name
FROM
    users u
JOIN
    user_courses uc ON u.id = uc.user_id
JOIN
    courses c ON uc.course_id = 1
JOIN 
    users us ON us.id = c.teacher
JOIN
    courses_videos cv ON c.id = cv.course_id
JOIN
    videos v ON cv.video_id = v.id
JOIN
    categories cat ON c.category_id = cat.id
WHERE
    c.id = 1;

---consulta alumnos, maestros, categoria y videos del curso 2

SELECT
    u.name AS user_name,
    v.title AS video_title,
    c.title AS course_title,
    us.name AS teacher_name, 
    c.level AS course_level,
    c.description AS course_description,
    cat.name AS category_name
FROM
    users u
JOIN
    user_courses uc ON u.id = uc.user_id
JOIN
    courses c ON uc.course_id = 2
JOIN 
    users us ON us.id = c.teacher
JOIN
    courses_videos cv ON c.id = cv.course_id
JOIN
    videos v ON cv.video_id = v.id
JOIN
    categories cat ON c.category_id = cat.id
WHERE
    c.id = 2;





